### ISSUE TITLE
ページ跨いでのSocket.IOの使い方を調べる

### ISSUE THREAD

**Issue by takumihara** [usatie/pong#136]
## 問題整理

- マッチング -> ゲーム画面に行く時に、1回目だけ、/pong にconnectができない
- 100%再現可能とおもったら再現できなくなった。。。
- たぶん、socket.IOのrace condition（disconnectしようとしながら、connectするから）。ソースコード見に行ったけど、非同期処理してない？気がするから起きそうじゃないけど、わからん
- 一回ページを戻ってもう一回matchしてページ遷移するといける

## 解決策

常にオープンなsocketインスタンスを親コンポーネントで持っておく。どうせ、chatの通知するのに必要なんだし。(根本的な原因は分かってない。。。)

### [How to use with React | Socket.IO](https://socket.io/how-to/use-with-react#listeners-in-a-child-component)

> We strongly advise against registering event listeners in your child components, because it ties the state of the UI with the time of reception of the events: if the component is not mounted, then some messages might be missed.

### [How to use socket.io-client correctly in React app - DEV Community](https://dev.to/bravemaster619/how-to-use-socket-io-client-correctly-in-react-app-o65)

> I don't think it's good approach. It will work for very small projects, but for larger ones not so much. Mixing socket communication with React will become overwhelming as app will grow, because all of it will spread through entire project. I would separate data source from frontend components. Imho better method is to extract actions and datasource to another files and provide only api to front components (as react-redux does). It would provide flexibility. Especially when you need to access different data sources (ie. local storage + cookie + websocket + ajax). React shouldn't "care" about where data comes from, business logic or communication with server.

### [Combining React with Socket.io for real-time goodness | by Hendrik Swanepoel | DailyJS | Medium](https://medium.com/dailyjs/combining-react-with-socket-io-for-real-time-goodness-d26168429a34)

- いいねいっぱいついてる割にはレベル低かった

### うちの会社

- https://www.npmjs.com/package/react-use-websocket
- contextつかってglobalに持ってた

### [Namespaces | Socket.IO](https://socket.io/docs/v4/namespaces/)

`io` で複数インスタンスを作っても、通信を管理する `Manager` というのはキャッシュしてくれている。
また、 `connect` も通信のコネクトとは分離してくれているので、複数のnamspaceを同時に使う場合、 `connect`が1回づつそれぞれに送ってくれる。

![Screenshot 2023-12-17 at 2 05 22](https://github.com/usatie/pong/assets/69781798/0a9dcf52-ab3a-4314-8fb6-582c7f049115)

### [The Socket.IO protocol | Socket.IO](https://socket.io/docs/v4/socket-io-protocol/)

`40/[namespace]`でconnect。
`41/[namespace]`でdisconnect。

### [socket.io-client/lib/index.ts at b3f0cab1a0dc101a8aa6a23dc779758019b38a23 · socketio/socket.io-client](https://github.com/socketio/socket.io-client/blob/b3f0cab1a0dc101a8aa6a23dc779758019b38a23/lib/index.ts#L25)

<details><summary>cacheしてくれてるコード</summary>

```javascript
  const newConnection =
    opts.forceNew ||
    opts["force new connection"] ||
    false === opts.multiplex ||
    sameNamespace;

  let io: Manager;

  if (newConnection) {
    debug("ignoring socket cache for %s", source);
    io = new Manager(source, opts);
  } else {
    if (!cache[id]) {
      debug("new io instance for %s", source);
      cache[id] = new Manager(source, opts);
    }
    io = cache[id];
  }
```

</details>

### [How it works | Socket.IO](https://socket.io/docs/v4/how-it-works/#disconnection-detection)

diconnectionが起きる仕組みについての解説

### [RFC 6455 - The WebSocket Protocol](https://datatracker.ietf.org/doc/html/rfc6455)

>    Either peer can send a control frame with data containing a specified
   control sequence to begin the closing handshake (detailed in
   Section 5.5.1).  Upon receiving such a frame, the other peer sends a
   Close frame in response, if it hasn't already sent one.  Upon
   receiving _that_ control frame, the first peer then closes the
   connection, safe in the knowledge that no further data is
   forthcoming.

**Comment by usatie** [comment]
Globalに持つならcontext使うのが鉄板には感じますね〜！

**Comment by takumihara** [comment]
cleanup関数でdisconnectしなくていいのでは？
-> handleDisconnectでlogicを持っている

グローバルで持つ
->

**Comment by takumihara** [comment]
> connect/disconnectとは違うメソッド

- Clientサイドのページ移動なら問題ない
- 同じnamespaceに接続する（Gameページから一回離れてもう一回Gameページに行く）と、新しいコネクションが作られる
- ページのリロードすると、cleanup関数で `leave` を呼ぶ前に disconnectされて、`leave` イベントがサーバーに届かない <- disconnectのハンドラーは呼ばれてる

-> 毎回新しいコネクション作る

**Comment by takumihara** [comment]
> 毎回新しいコネクション作る

リフレッシュでももちろん動く

https://github.com/usatie/pong/pull/172

**Comment by takumihara** [comment]
> ページのリロードすると、cleanup関数で leave を呼ぶ前に disconnectされて、leave イベントがサーバーに届かない <- disconnectのハンドラーは呼ばれてる

leaveでもdisconnectでも退出のロジックを持てば解決する
